version: '3'
services:
  job-service:
    depends_on:
      - redis
    image: saas-interview-challenge1
    command: /app/job_service
    environment:
      - REDIS_URL=redis:6379
    ports:
    - "8000:8000"
  worker-service:
    depends_on:
      - redis
    image: saas-interview-challenge1
    environment:
      - REDIS_URL=redis:6379    
    command: /app/worker_service
  redis:
    image: redis
    # ports:
    # - "6379:6379"